version: '3.9'
services:
  backend-app:
    build:
      context: .
      dockerfile: local.Dockerfile
    # This run the app in development mode | To run in production mode, change the command to npm run start
    command: npm run dev
    ports:
      - '3001:3001'
    env_file: .env
    volumes:
      - './src:/app/src'
